### ISSUE TITLE
Execution of ngcpcfg fails with "Hook target directory /etc/ngcp-config/.git/hooks not a directory"

### ISSUE THREAD

**Issue by mmuhd** [sipwise/ngcpcfg#1]
I am trying to setup SIPWISE CE on AWS using your SIPWISE AMI, all was fine until I added SSL certs and trying to ngcpcfg apply 'added ssl', after editing the config.yml files, all commands returns
``` 
Error: Hook target directory /etc/ngcp-config/.git/hooks not a directory. Exiting.
```
Please help, I am new to the platform.

**Comment by mika** [comment]
@mmuhd as a starting point, which Sipwise CE version are you running? Which AMI exactly did you choose?

**Comment by mmuhd** [comment]
Hi @mika This is the AMI I used: `ami-0f11f240b0c68c0ae`
The issue is still persisting.
Thank you.

**Comment by mika** [comment]
Ok, so this is Sipwise CE version mr8.5.3. I sadly can't reproduce your issue (tested with the AMI you used).

Did  you follow instructions from https://www.sipwise.com/doc/mr8.5.3/spce/?_href=ar01s17.html#_ssl_certificates?

What's the output of:

```
sudo ls -la /etc/ngcp-config/.git/
sudo ls -la /etc/ngcp-config/.git/hooks/
```

on your system? 

Furthermore, please provide more details what you exactly did (most notable the commands you executed and the changes applied to `/etc/ngcp-config/`), so we've a chance to reproduce your issue.

**Comment by mmuhd** [comment]
Oh I got it thanks @mika I resolved it by adding the hwaddr at /etc/ngcp-config/network.yml. Now everything is fine, Thanks a lot.

**Comment by mmuhd** [comment]
Hi @mika I resort to using 9.1.1 it is working just fine. Thanks a lot.
